on: [push, pull_request]

name: test-shiny-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Restore renv package cache
        uses: r-lib/actions/setup-renv@v2
        # This will run renv::restore() automatically 
        # and bypass any auto-dependency discovery.

      - name: Run tests
        run: Rscript -e 'testthat::test_dir("tests/testthat")'