on: [push, pull_request]

name: test-shiny-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libproj-dev libpng-dev libudunits2-dev libx11-dev pandoc

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Restore renv package cache
        uses: r-lib/actions/setup-renv@v2

      - name: Run tests
        run: Rscript -e 'testthat::test_dir("tests/testthat")'